cacheFolder: .yarn/cache

enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  "@typescript-eslint/project-service@*":
    dependencies:
      typescript: "*"
  eslint-plugin-jest@*:
    peerDependencies:
      typescript: "*"

pnpMode: loose
